# Generated by Django 4.1.5 on 2023-07-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
